\documentclass{beamer}\usetheme{boxes}

\usepackage{amsmath,hyperref,bbding}
\usepackage{todonotes}

\newcommand{\bskip}{\\~\\}

\newcommand{\checkitem}{\item[\Checkmark]}
\newcommand{\xitem}{\item[\XSolidBrush]}
\newcommand{\mehitem}{\item[$\approx$]}
\newcommand{\easyframe}[2]{\frame{\frametitle{#1}
#2
}}

\author[CABP-BHS]{Carl~A.~B.~Pearson \&\ Burton~H.~Singer}
\institute[UF]{University of Florida, Emerging Pathogens Institute}
\begin{document}
\SweaveOpts{concordance=TRUE}
\title{MURI 2013 Review}
\institute[University of Florida]{Emerging Pathogens Institute, University of Florida}

\frame{\titlepage}

\easyframe{Overview}{
\begin{itemize}
\item<1-> development of simulation framework,
\item<2-> intra-MURI projects,
\item<3-> extra-MURI projects
\end{itemize}
% notes-notes-notes
}

\easyframe{Simulation Framework}{
Basic problem: lots of graph metrics, so what?
\begin{itemize}
  \item<2-> Limited closure of inductive-deductive loop
  \item<3-> Experimental options restricted
  \item<4-> So: want simple tool to simulate mechanics
\end{itemize}
% notes-notes-notes
}

\easyframe{Simulation Framework}{
``Simple'' == reduced syntax + piping connecting
\begin{itemize}
  \item<2-> initial graph generation
  \item<3-> dynamic graph evolution
  \item<4-> ``message'' passing and observation model
  \item<5-> agent-to-agent behavior
  \item<6-> agent-to-broadcast (and {\em vv}.) behavior
  \item<7-> interventions
  \item<8-> plus computational concerns (e.g., IO, cluster computation)
\end{itemize}
% notes-notes-notes
}

\easyframe{Simulation Framework Progress}{
\begin{itemize}
  \mehitem initial graph generation (on-going work w/ Ed/Edo re correlated interaction types)
  \xitem dynamic graph evolution
  \checkitem ``message'' passing and observation model
  \checkitem agent-to-agent behavior
  \xitem agent-to-broadcast (and vv.) behavior
  \xitem interventions
  \mehitem plus computational concerns (e.g., IO, cluster computation)
\end{itemize}
% notes-notes-notes
}

\easyframe{Simulation Framework Progress}{

}

\easyframe{Results Reported at Sunbelt}{
Worked w/ Edo \&\ Ed to prepare basic simulated communications
\begin{itemize}
  \item simple graph generation:
  \begin{itemize}
    \item mixed interaction types
    \item households into communities
    \item clandestine manager + cliqued groups of subordinates
  \end{itemize}
  \item simple message passing - ``Good'' vs. ``Bad'', time-independent probabilities
\end{itemize}
% notes-notes-notes
}

\easyframe{Sample Population Graphs}{
\missingfigure{show mixed interaction types}
% notes-notes-notes
}

\easyframe{Sample Population Graphs}{
\missingfigure{highlight particular interaction types}
% notes-notes-notes
}

\easyframe{Sample Results Analysis}{
\missingfigure{toss in sunbelt example}
% notes-notes-notes
}

\easyframe{Aside on Results}{
Measured strategies as TPR and FPR (sensitivity and 1 - specificity) over time, with fixed strategy criteria.

ROC could capture TPR vs FPR over criteria -- measure ROC scalar (e.g., discrimination) time evolution?

Even more complicated surface with several internal setpoints
% notes-notes-notes
}

\easyframe{Intra-MURI Projects}{
\begin{itemize}
\item Airoldi / Kao -- implement more sophisticated conditional tie generators
\item Lazer et al. -- simulate firm-induced vs background political donations
\item Shapiro -- identification with evolving SIMs, and using telephony data to parametrize graph generation
\end{itemize}
% notes-notes-notes
}

\easyframe{Intra-MURI Project: Lazer et al. Collaboration}{
Brief Detailed Note
\begin{itemize}
\item<1-> sample a size distribution for firms,
\item<2-> until desired population size generated
\item<3-> randomly assign political preferences (A vs. B)\footnote{We use a uniform sample; seems reasonable to assume that there would be assortativity within firms.}
\end{itemize}
% We'll let Lazer's group speak to their specific work, and stick to what we're doing to support that.
% in brief, we take a firm size distribution
}

\easyframe{Extra-MURI Projects}{
\begin{itemize}
\item D. Bright, UNSW -- agent/process-based models of meth production
\item K. Carley, CMU -- adding broadcast/mean-field perspectives to agent-models
\item SAIC/L. Gerdes, USMA -- geo-temporal hashing, specifically estimating between-observation distribution
\item N. Roberts and S. Everton, NPGS -- dynamic growth of Noordin network
\item Assorted EPI -- cryptic infections (equivalent to rumor spreading source ID), using large Montreal WiFi access metadata
\end{itemize}
% notes-notes-notes
}

\easyframe{Extra-MURI Projects, David Bright}{
\missingfigure{meth network highlighting players of different roles}
% notes-notes-notes
}

\easyframe{Extra-MURI Projects, Kathleen Carley}{
\missingfigure{ORA logo - unfortunately, other part is under NDA, though they are supposed to be used in tandem}
% notes-notes-notes
}

\easyframe{Extra-MURI Projects, SAIC/Luke Gerdes}{
\missingfigure{mostly about applying kinematics + diffusion theory to describe probability distribution of multiple actors between observations}
% notes-notes-notes
}

\easyframe{Extra-MURI Projects, Nancy Roberts \&\ Sean Everton}{
\missingfigure{Some of their Noordin results?}
% notes-notes-notes
}

\easyframe{Extra-MURI Projects, EPI}{
Mostly focused on large, anonymized data set of Montreal municipal WiFi access.

Tracking spread of cryptic pathogen analogous to tracking rumor to source
% notes-notes-notes
}

\end{document}